// This file is released under the 3-clause BSD license. See COPYING-BSD.
// Generated by tbx_build_help_loader: Please, do not edit this file

add_help_chapter("scilab_octave",get_absolute_file_path("addchapter.sce"),%F);
clear add_help_chapter;
