// This file is released under the 3-clause BSD license. See COPYING-BSD.
// Generated by builder_gateway.sce: Please, do not edit this file

sci_gateway_dir = get_absolute_file_path("cleaner_gateway.sce");
current_dir     = pwd();

chdir(sci_gateway_dir);
if ( isdir("cpp") ) then
    chdir("cpp");
    exec("cleaner.sce");
    mdelete("cleaner.sce");
end

chdir(current_dir);
clear sci_gateway_dir current_dir;
